-- Authentication for the single local CRM administrator. Password material is
-- deliberately isolated from the application user profile.
CREATE TABLE local_credentials (
  user_id uuid PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
  singleton boolean NOT NULL DEFAULT true UNIQUE CHECK (singleton = true),
  password_hash text NOT NULL,
  password_changed_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (password_hash ~ '^scrypt[$]v=1[$]n=32768,r=8,p=3,l=64[$][A-Za-z0-9_-]{22}[$][A-Za-z0-9_-]{86}$')
);

CREATE TABLE auth_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  token_digest char(64) NOT NULL UNIQUE CHECK (token_digest ~ '^[0-9a-f]{64}$'),
  csrf_digest char(64) NOT NULL CHECK (csrf_digest ~ '^[0-9a-f]{64}$'),
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  idle_expires_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_ip_hash char(64),
  user_agent text,
  CHECK (idle_expires_at <= expires_at),
  CHECK (expires_at > created_at)
);

CREATE INDEX auth_sessions_user_active_idx
  ON auth_sessions (user_id, expires_at)
  WHERE revoked_at IS NULL;
CREATE INDEX auth_sessions_cleanup_idx
  ON auth_sessions (expires_at, idle_expires_at, revoked_at);

-- Persistent per-network throttling works across Render restarts and replicas.
-- The key is an HMAC generated by requestContext; no raw address is stored.
CREATE TABLE auth_login_throttles (
  key_hash char(64) PRIMARY KEY CHECK (key_hash ~ '^[0-9a-f]{64}$'),
  window_started_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  blocked_until timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX auth_login_throttles_cleanup_idx
  ON auth_login_throttles (updated_at, blocked_until);

CREATE TRIGGER local_credentials_set_updated_at BEFORE UPDATE ON local_credentials
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
